#:schema node_modules/wrangler/config-schema.json
name = "pdf-to-word-new"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

# Cloudflare Pages 部署配置
[build]
command = ""
publish = "static"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
